language: python

matrix:
    include:
        - name: 'Latest: Linux, Python 3.8 & Node.js 12'
          dist: xenial
          python: '3.8'
          env:
              - NODE_VERSION=12
        - name: 'Python 3.7'
          dist: xenial
          python: '3.7'
          env:
              - NODE_VERSION=12
        - name: 'Python 3.6'
          dist: xenial
          python: '3.6'
          env:
              - NODE_VERSION=12
        - name: 'Python 3.5'
          dist: xenial
          python: '3.5'
          env:
              - NODE_VERSION=12
        - name: 'Node.js 10'
          dist: xenial
          python: '3.8'
          env:
              - NODE_VERSION=10
        - name: 'Node.js 8'
          dist: xenial
          python: '3.8'
          env:
              - NODE_VERSION=8
        - name: 'Mac OS'
          dist: osx
          python: '3.8'
          env:
              - NODE_VERSION=12

addons:
  apt:
    packages:
      - jq

cache:
    pip: true
    npm: true
    directories:
      - /home/travis/.betty/betty.plugins.js.Js

before_install:
    - nvm install "$NODE_VERSION"

install:
    - ./bin/build-dev

script:
    - ./bin/test

after_success:
    - codecov
