name: Test

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: 'Python 3.10'
            os: ubuntu-latest
            python: '3.10'
          - name: 'Python 3.9'
            os: ubuntu-latest
            python: '3.9'
          - name: 'Python 3.8'
            os: ubuntu-latest
            python: '3.8'
          - name: 'Python 3.7'
            os: ubuntu-latest
            python: '3.7'
          - name: 'Mac OS'
            os: macos-latest
            # @todo Mac OS builds with Python 3.10 fail for some reason when building pip dependencies. Let's use
            # @todo Python 3.9 for Mac OS until we know more about Python 3.10 compatibility.
            python: '3.9'
          - name: 'Windows'
            os: windows-latest
            # @todo Windows builds with Python 3.10 fail for some reason when building pip dependencies. Let's use
            # @todo Python 3.9 for Windows until we know more about Python 3.10 compatibility.
            python: '3.9'

    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install APT dependencies
        if: startsWith(runner.os, 'Linux')
        run: sudo apt-get install herbstluftwm libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libxml2-dev libxslt1-dev xvfb

      - name: Launch the window manager
        if: startsWith(runner.os, 'Linux')
        run: |
          herbstluftwm &
          sleep 1

      - name: Install Homebrew dependencies
        if: startsWith(runner.os, 'macOS')
        run: brew install shellcheck

      - name: Install Chocolatey dependencies
        if: startsWith(runner.os, 'Windows')
        run: choco install shellcheck

      - name: Build the development environment
        run: |
          ./bin/build-dev
        shell: bash

      - name: Get the pip cache directory path
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache the pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Get the npm cache directory path
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache the npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run the tests
        run: |
          ./bin/test
        shell: bash

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
